CREATE DATABASE RH;

USE RH;

CREATE TABLE FUNCIONARIOS( 
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (100),
FUNCAO CHAR (255),
IDADE INT,
SETOR CHAR (255),
SALARIO DOUBLE,
PRIMARY KEY (ID)
);

INSERT INTO FUNCIONARIOS (NOME, FUNCAO, IDADE, SETOR, SALARIO) VALUES ("MARIA", "RECEPCIONISTA", 20, "ADMINISTRATIVO", 1530);
INSERT INTO FUNCIONARIOS (NOME, FUNCAO, IDADE, SETOR, SALARIO) VALUES ("JOAO", "PORTEIRO", 31, "PORTARIA", 3000);
INSERT INTO FUNCIONARIOS (NOME, FUNCAO, IDADE, SETOR, SALARIO) VALUES ("JOSE", "SEGURANÇA", 42, "SEGURANÇA", 4300);
INSERT INTO FUNCIONARIOS (NOME, FUNCAO, IDADE, SETOR, SALARIO) VALUES ("PEDRO", "MOTO BOY", 27, "ADMINISTRATIVO", 1850);
INSERT INTO FUNCIONARIOS (NOME, FUNCAO, IDADE, SETOR, SALARIO) VALUES ("TEREZA", "GERENTE", 35, "ADMINISTRATIVO", 3800);

SELECT * FROM FUNCIONARIOS WHERE SALARIO > 2000;

SELECT * FROM FUNCIONARIOS WHERE SALARIO < 2000;	

SELECT * FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET SALARIO = 4100 WHERE ID = 4;