CREATE DATABASE E_COMMERCE;

USE E_COMMERCE;

CREATE TABLE PRODUTOS( 
ID BIGINT AUTO_INCREMENT,
TIPO CHAR (100),
TAMANHO CHAR (255),
COR CHAR (255),
QUANTIDADE INT,
PRECO DOUBLE,
PRIMARY KEY (ID)
);

INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("CALÇA", "GG", "PRETO", 3, 800);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("BERMUDA", "PP", "AMARELO", 5, 650);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("CAMISA", "P", "AZUL", 2, 720);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("SAIA", "M", "VERDE", 8, 350);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("SHORTS", "G", "ROSA", 4, 460);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("VESTIDO", "G", "ROXO", 7, 490);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("REGATA", "P", "BRANCO", 1, 320);
INSERT INTO PRODUTOS (TIPO, TAMANHO, COR, QUANTIDADE, PRECO) VALUES ("CASACO", "G", "MARROM", 4, 1060);

SELECT * FROM PRODUTOS WHERE PRECO > 500;

SELECT * FROM PRODUTOS WHERE PRECO < 500;	

SELECT * FROM PRODUTOS;

UPDATE PRODUTOS SET COR = "LARANJA" WHERE ID = 3;

SELECT * FROM PRODUTOS WHERE ID = 3;

DELETE FROM PRODUTOS WHERE ID = 9;