CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
DOCE VARCHAR (255),
SALGADA VARCHAR (255)
);

-- ALTERAR NOME DE COLUNA NA TABELA
ALTER TABLE TB_CATEGORIAS 
CHANGE SALGADA COZINHA VARCHAR(255);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (255),
MASSA VARCHAR(255),
PRECO DECIMAL,
TAMANHO VARCHAR(255),
CATEGORIAS_ID BIGINT,
FOREIGN KEY(CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

ALTER TABLE TB_PIZZAS CHANGE TAMANHO TIPO VARCHAR(255);

INSERT INTO TB_CATEGORIAS (TAMANHO, COZINHA) 
VALUES
("BROTO", "VEGANA"),
("MEDIA", "VEGANA"),
("GRANDE", "VEGANA"),
("BROTO", "TRADICIONAL"),
("MEDIA", "TRADICIONAL"),
("GRANDE", "TRADICIONAL");


INSERT INTO TB_PIZZAS (NOME, MASSA, PRECO, TIPO, CATEGORIAS_ID)
VALUES 
("MUSSARELA", "FINA", 35.00, "SALGADA",4),
("CALABRESA", "FINA", 40.00, "SALGADA",3),
("PALMITO", "GROSSA", 55.00, "SALGADA",2),
("BRÓCOLIS", "FINA", 30.00, "SALGADA",1),
("FRANGO", "GROSSA", 50.00, "SALGADA",4),
("BRIGADEIRO", "GROSSA", 40.00, "DOCE",3),
("CHURROS", "GROSSA", 35.00, "DOCE",2),
("ROMEU E JULIETA", "FINA", 40.00, "DOCE",1);

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;

SELECT * FROM TB_PIZZAS WHERE PRECO >50.00  && PRECO <100.00;

SELECT * FROM TB_PIZZAS WHERE NOME LIKE "%M%";

SELECT NOME, MASSA, PRECO, TIPO, TAMANHO, COZINHA FROM  TB_PIZZAS 
INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID;

SELECT * FROM  TB_PIZZAS 
INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID 
WHERE TIPO LIKE "%DOCE%";